const Erros = {
  NOME_CARACTERES_ESPECIAIS: "NOME_CARACTERES_ESPECIAIS",
  NOME_GRANDE: "NOME_GRANDE",
  NOME_PEQUENO: "NOME_PEQUENO",
  NOME_SEM_SOBRENOME: "NOME_SEM_SOBRENOME",
  NOME_VAZIO: "NOME_VAZIO",

  ID_INVALIDO: "ID_INVALIDO",

  CPF_INVALIDO: "CPF_INVALIDO",

  SENHA_INVALIDA: "SENHA_INVALIDA",
} as const;

export default Erros;
